In [16]:
!pip install numpy

In [17]:
import numpy as np

In [ ]:
#1D array

In [21]:
x=np.arange(6)
print(x)

[0 1 2 3 4 5]


In [22]:
x.shape

(6,)

In [ ]:
#2d array

In [24]:
y=np.arange(8).reshape(2,4)
print(y)

[[0 1 2 3]
 [4 5 6 7]]


In [25]:
y.shape

(2, 4)

In [ ]:
#3D Array

In [26]:
z=np.arange(24).reshape(2,2,6)
print(z)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]


In [ ]:
#arithmetic operations

In [27]:
a=np.array([5,5,5,5,5])
b=np.array([3,3,3,3,3])

In [28]:
print(a+b)

[8 8 8 8 8]


In [29]:
print(a-b)

[2 2 2 2 2]


In [30]:
print(a<b)

[False False False False False]


In [31]:
print(a>b)

[ True  True  True  True  True]


In [33]:
print(a*b)

[15 15 15 15 15]


In [34]:
print(a**2)

[25 25 25 25 25]


In [35]:
print(b**3)

[27 27 27 27 27]


In [36]:
print(a/b)

[1.66666667 1.66666667 1.66666667 1.66666667 1.66666667]


In [37]:
print(a)
print(b)

[5 5 5 5 5]
[3 3 3 3 3]


In [ ]:
#modifying an existing array

In [38]:
a*=2

In [39]:
print(a)

[10 10 10 10 10]


In [40]:
a+=b

In [41]:
print(a)

[13 13 13 13 13]


In [42]:
b+=a

In [43]:
print(b)

[16 16 16 16 16]


In [ ]:
#unary operations

In [44]:
wages=np.array([20000,50000,40000,10000,35000])

In [45]:
wages.min()

10000

In [46]:
wages.max()

50000

In [47]:
wages.sum()

155000

In [ ]:
#calclulate sum of cols and rows separately

In [48]:
print(y)

[[0 1 2 3]
 [4 5 6 7]]


In [ ]:
axis 0 --->cols
axis 1 --->rows

In [49]:
y.sum(axis=0)

array([ 4,  6,  8, 10])

In [50]:
y.sum(axis=1)

array([ 6, 22])