In [4]:
import numpy as np

In [12]:
sal=np.genfromtxt('salary.csv',delimiter=',')
sal

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [16]:
mean=np.mean(sal)
median=np.median(sal)
variance=np.var(sal)
sd=np.std(sal)

In [20]:
print('Mean=%i'%mean)
print('Median=%i'%median)
print('Variance=%i'%variance)
print('sd=%i'%sd)

Mean=55894
Median=48000
Variance=3043770333
sd=55170


In [25]:
s=np.arange(1, 20, 2)
s

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
iteration in numpy:

In [26]:
a=np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [ ]:
single dimensonal array

In [27]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0


In [ ]:
multidimensional array

In [45]:
students=np.array([['aaa','bbb','ccc','ddd','eee'],
                   [90,80,75,60,67],
                   [100,90,80,70,60]])


In [46]:
for i in students:
    print('i=',i)

i= ['aaa' 'bbb' 'ccc' 'ddd' 'eee']
i= ['90' '80' '75' '60' '67']
i= ['100' '90' '80' '70' '60']


In [47]:
for i in students.flatten():
    print(i)

aaa
bbb
ccc
ddd
eee
90
80
75
60
67
100
90
80
70
60


In [48]:
for s in students.flatten(order='F'):
    print(s)

aaa
90
100
bbb
80
90
ccc
75
80
ddd
60
70
eee
67
60
