In [ ]:
***nditer***
###iterator for arrays###

In [2]:
import numpy as np

In [3]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [4]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
for i in np.nditer(b):  ##row based iteration
    print(i*2)

0
2
4
6
8
10
12
14
16
18
20
22


In [9]:
for i in np.nditer(b,order='F'):  ##col based iteration
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [ ]:
****splitting arrays****

In [12]:
x=np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
split this array into 5 equal parts


In [14]:
np.split(x,3)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

In [15]:
np.split(x,5)

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11]),
 array([12, 13, 14])]

In [16]:
s=np.array([('india','china','nepal','bangladesh'),('US','UK','USSR','NZ')])

In [17]:
s

array([['india', 'china', 'nepal', 'bangladesh'],
       ['US', 'UK', 'USSR', 'NZ']], dtype='<U10')

In [ ]:
###horizontal splitting

In [18]:
z1,z2=np.hsplit(s,2)

In [26]:
z1,z2=np.hsplit(s,4)

ValueError: too many values to unpack (expected 2)

In [27]:
print(z1)

[['india' 'china']
 ['US' 'UK']]


In [28]:
print(z2)

[['nepal' 'bangladesh']
 ['USSR' 'NZ']]


In [ ]:
###vertical splitting

In [23]:
z3,z4=np.vsplit(s,2)

In [24]:
print(z3)

[['india' 'china' 'nepal' 'bangladesh']]


In [25]:
print(z4)

[['US' 'UK' 'USSR' 'NZ']]
